version: "3.9"
services:
  db:
    image: postgis/postgis:14-master
    shm_size: 16gb
    container_name: bcfishpass-db
    command: postgres -c default_statistics_target=100 -c max_connections=100 -c max_locks_per_transaction=64 -c checkpoint_timeout=30min -c maintenance_work_mem=1GB -c effective_cache_size=16GB -c work_mem=500MB -c max_wal_size=10GB -c wal_buffers=16MB -c shared_buffers=8GB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_DATABASE=bcfishpass
  client:
    build: .
    container_name: bcfishpass-client
    volumes:
      - "./:/home/bcfishpass"
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bcfishpass
    depends_on:
      db:
        condition: service_healthy
  featureserv:
    image: pramsey/pg_featureserv:latest
    container_name: bcfishpass-fs
    ports:
      - ${TS_PORT}:9000
    volumes:
      - "./:/home/bcfishpass"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bcfishpass
    depends_on:
      db:
        condition: service_healthy
  tileserv:
    image: pramsey/pg_tileserv:latest
    container_name: bcfishpass-ts
    ports:
      - ${FS_PORT}:7800
    volumes:
      - "./:/home/bcfishpass"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bcfishpass
    depends_on:
      db:
        condition: service_healthy