name: bcfishpass
channels:
  - conda-forge
  - defaults
dependencies:
  - make
  - wget
  - zip
  - unzip
  - parallel
  - cdo
  - libpq
  - gdal>=3.4
  - python=3.9
  - pip
  - requests
  - owslib
  - geopandas>=0.10.2
  - psycopg2
  - jq
  - rasterstats
  - pip:
      - bcdata>=0.5.1
variables:
  PGHOST: localhost
  PGUSER: postgres
  PGPORT: 5432
  PGDATABASE: bcfishpass
  DATABASE_URL: postgresql://postgres@localhost:5432/bcfishpass